version: '3'
services:
  e_sequel_db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_sequel
      MYSQL_USER: e_sequel
      MYSQL_PASSWORD: e_sequelpassword
    volumes:
      - ./challenge/sql:/docker-entrypoint-initdb.d
  e_sequel:
    build: .
    restart: always
    ports:
      - 10000:80
    volumes:
      - ./challenge/html:/var/www/html/
    depends_on:
      - e_sequel_db
