version: '3'
services:
  shopkeeper:
    build:
      context: .
    working_dir: /home/pwn
    container_name: shopkeeper
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9004"
    entrypoint: /etc/init.sh
